name: geochem
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.6.2=pyhd8ed1ab_0
  - aom=3.5.0=hf0c8a7f_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - bleach=6.0.0=pyhd8ed1ab_0
  - brotli=1.0.9=hb7f2c08_8
  - brotli-bin=1.0.9=hb7f2c08_8
  - bzip2=1.0.8=h0d85af4_4
  - c-ares=1.19.1=h0dc2134_0
  - ca-certificates=2023.5.7=h8857fd0_0
  - cairo=1.16.0=h09dd18c_1016
  - certifi=2023.5.7=pyhd8ed1ab_0
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.3=pyhd8ed1ab_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dav1d=1.2.0=h0dc2134_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hf0c8a7f_1
  - ffmpeg=6.0.0=gpl_h9b64a9e_101
  - flit-core=3.9.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h5bb23bf_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h3f81eb7_1
  - fribidi=1.0.10=hbcb3906_0
  - geos=3.11.2=hf0c8a7f_0
  - gettext=0.21.1=h8a4c099_0
  - glib=2.76.3=h7d26f99_0
  - glib-tools=2.76.3=h7d26f99_0
  - gmp=6.2.1=h2e338ed_0
  - gnutls=3.7.8=h207c4f0_0
  - graphite2=1.3.13=h2e338ed_1001
  - gst-plugins-base=1.22.3=hb5d3a86_1
  - gstreamer=1.22.3=h53e17e3_1
  - harfbuzz=7.3.0=h413ba03_0
  - icu=72.1=h7336db1_0
  - idna=3.4=pyhd8ed1ab_0
  - imageio=2.28.1=pyh24c5eb1_0
  - imageio-ffmpeg=0.4.8=pyhd8ed1ab_0
  - importlib-metadata=6.6.0=pyha770c72_0
  - importlib_metadata=6.6.0=hd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - ipykernel=6.23.1=pyh736e0ef_0
  - ipython=8.13.2=pyhd1c38e8_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.0.6=pyhd8ed1ab_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_client=8.2.0=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py311h6eed73b_0
  - jupyter_events=0.6.3=pyhd8ed1ab_0
  - jupyter_server=2.6.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.7=pyhd8ed1ab_1
  - krb5=1.20.1=h049b76e_0
  - lame=3.100=hb7f2c08_1003
  - lcms2=2.15=h2dcdeff_1
  - lerc=4.0.0=hb486fe8_0
  - libass=0.17.1=h66d2fa1_0
  - libblas=3.9.0=16_osx64_openblas
  - libbrotlicommon=1.0.9=hb7f2c08_8
  - libbrotlidec=1.0.9=hb7f2c08_8
  - libbrotlienc=1.0.9=hb7f2c08_8
  - libcblas=3.9.0=16_osx64_openblas
  - libclang=14.0.6=default_hd95374b_1
  - libclang13=14.0.6=default_habbcc1a_1
  - libcurl=8.1.1=hbee3ae8_0
  - libcxx=16.0.4=hd57cbcb_0
  - libdeflate=1.18=hac1461d_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libexpat=2.5.0=hf0c8a7f_1
  - libffi=3.4.2=h0d85af4_5
  - libgfortran=5.0.0=11_3_0_h97931a8_31
  - libgfortran5=12.2.0=he409387_31
  - libglib=2.76.3=hc62aa5d_0
  - libiconv=1.17=hac89ed1_0
  - libidn2=2.3.4=hb7f2c08_0
  - libjpeg-turbo=2.1.5.1=hb7f2c08_0
  - liblapack=3.9.0=16_osx64_openblas
  - libllvm14=14.0.6=hc8e404f_2
  - libnghttp2=1.52.0=he2ab024_0
  - libogg=1.3.4=h35c211d_1
  - libopenblas=0.3.21=openmp_h429af6e_3
  - libopus=1.3.1=hc929b4f_1
  - libpng=1.6.39=ha978bb4_0
  - libpq=15.3=h9dc22bb_1
  - libsodium=1.0.18=hbcb3906_1
  - libsqlite=3.42.0=h58db7d2_0
  - libssh2=1.10.0=h47af595_3
  - libtasn1=4.19.0=hb7f2c08_0
  - libtiff=4.5.0=hedf67fa_6
  - libunistring=0.9.10=h0d85af4_0
  - libvorbis=1.3.7=h046ec9c_0
  - libvpx=1.13.0=hf0c8a7f_0
  - libwebp-base=1.3.0=hb7f2c08_0
  - libxcb=1.15=hb7f2c08_0
  - libxml2=2.11.4=hd95e348_0
  - libzlib=1.2.13=hfd90126_4
  - llvm-openmp=16.0.4=hff08bdf_0
  - matplotlib-base=3.7.1=py311h2bf763f_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=2.0.5=pyhd8ed1ab_0
  - moviepy=1.0.3=pyhd8ed1ab_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.32=hc6116ba_2
  - mysql-libs=8.0.32=haa61052_2
  - nbclassic=1.0.0=pyhb4ecaf3_1
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert=7.4.0=pyhd8ed1ab_0
  - nbconvert-core=7.4.0=pyhd8ed1ab_0
  - nbconvert-pandoc=7.4.0=pyhd8ed1ab_0
  - nbformat=5.8.0=pyhd8ed1ab_0
  - ncurses=6.3=h96cf925_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nettle=3.8.1=h96f3785_1
  - notebook=6.5.4=pyha770c72_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - nspr=4.35=hea0b92c_0
  - nss=3.89=h78b00b3_0
  - openh264=2.3.1=hf0c8a7f_2
  - openjpeg=2.5.0=h13ac156_2
  - openssl=3.1.0=h8a1eda9_3
  - overrides=7.3.1=pyhd8ed1ab_0
  - p11-kit=0.24.1=h65f8906_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandoc=2.19.2=h694c41f_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre2=10.40=h1c4e4bc_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=hbcb3906_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.5.1=pyhd8ed1ab_0
  - ply=3.11=py_1
  - pooch=1.7.0=pyha770c72_3
  - proglog=0.1.9=py_0
  - proj=9.2.0=hf909084_0
  - prometheus_client=0.17.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - pthread-stubs=0.4=hc929b4f_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.7=py311h8771221_3
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.3=h99528f9_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.17.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.11=3_cp311
  - qt-main=5.15.8=h0afe88e_10
  - qtconsole=5.4.3=pyhd8ed1ab_0
  - qtconsole-base=5.4.3=pyha770c72_0
  - qtpy=2.3.1=pyhd8ed1ab_0
  - readline=8.2=h9e318b2_1
  - requests=2.31.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - send2trash=1.8.2=pyhd1c38e8_0
  - setuptools=67.7.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.42.0=h2b0dec6_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - svt-av1=1.5.0=he965462_0
  - terminado=0.17.1=pyhd1c38e8_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h5dbffcc_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.6.2=hd8ed1ab_0
  - typing_extensions=4.6.2=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2023c=h71feb2d_0
  - urllib3=2.0.2=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.5.2=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.7=pyhd8ed1ab_0
  - x264=1!164.3095=h775f41a_2
  - x265=3.5=hbb4e6a2_3
  - xorg-libxau=1.0.11=h0dc2134_0
  - xorg-libxdmcp=1.1.3=h35c211d_0
  - xz=5.2.6=h775f41a_0
  - yaml=0.2.5=h0d85af4_2
  - zeromq=4.3.4=he49afe7_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=hfd90126_4
  - zstd=1.5.2=hbc0c0cd_6
  - pip:
    - argon2-cffi-bindings==21.2.0
    - cartopy==0.21.1
    - cffi==1.15.1
    - contourpy==1.0.7
    - debugpy==1.6.7
    - fonttools==4.39.4
    - jupyter==1.0.0
    - jupyter-core==5.3.0
    - kiwisolver==1.4.4
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - numpy==1.24.3
    - pillow==9.5.0
    - psutil==5.9.5
    - pyobjc-core==9.1.1
    - pyobjc-framework-cocoa==9.1.1
    - pyproj==3.5.0
    - pyqt5==5.15.7
    - pyqt5-sip==12.11.0
    - pyrsistent==0.19.3
    - pyyaml==6.0
    - pyzmq==25.0.2
    - scipy==1.10.1
    - shapely==2.0.1
    - sip==6.7.9
    - tornado==6.3.2
